// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lmefnzptpkpbsihavzkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxtZWZuenB0cGtwYnNpaGF2emtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4OTI2NTYsImV4cCI6MjA2NTQ2ODY1Nn0.LdJ6Nhhhy_XAlNDwQrY5LH37E0WKZ1e03Szj9FxsHrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);